INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (1, N'Apple', 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (2, N'Orange', 7, NULL, CAST(7.0000 AS Money))
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (3, N'Lemon', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (4, N'Lime', 2, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (5, N'Cherry', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (6, N'Kiwi', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (7, N'Olive', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (8, N'Banana', 3, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (9, N'Lemon', 1, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (10, N'Cucumber', 2, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (11, N'Blackberries', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (12, N'Lemon Peel', NULL, NULL, NULL)
INSERT INTO [dbo].[Fruit] ([Id], [Name], [Аmount], [Shelf life], [Price]) VALUES (13, N'Orange', 1, NULL, NULL)
