INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (1, N'Garnet juice', 3, N'00:00:00', CAST(3.0000 AS Money))
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (2, N'Cherry juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (3, N'Pineapple juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (4, N'Apple juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (5, N'Orange juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (6, N'Lime juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (7, N'Cherry Juice', 2, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (8, N'Fruit Juice', 1, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (9, N'Lemon Juice', NULL, NULL, NULL)
INSERT INTO [dbo].[Juice] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (10, N'Raspberry Juice', NULL, NULL, NULL)
