INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (1, N'Cola', 5, N'00:00:00', CAST(5.0000 AS Money))
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (2, N'Coca-Cola', 6, NULL, CAST(6.0000 AS Money))
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (3, N'Pepsi', 7, NULL, CAST(7.0000 AS Money))
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (4, N'Fanta', 6, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (5, N'Dr. Pepper', 2, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (6, N'Fanta', 3, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (7, N'Mountain Dew', NULL, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (8, N'Schweppes', 3, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (9, N'7-Up', 2, NULL, NULL)
INSERT INTO [dbo].[Soda] ([Id], [Name], [Capacity], [Shelf life], [Price]) VALUES (10, N'Cherry Cola', 2, NULL, NULL)
