INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (1, N'Light rum', N'https://www.thecocktaildb.com/images/ingredients/Light%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (2, N'Applejack', N'https://www.thecocktaildb.com/images/ingredients/Applejack.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (3, N'Gin', N'https://www.thecocktaildb.com/images/ingredients/Gin.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (4, N'Dark rum', N'https://www.thecocktaildb.com/images/ingredients/Dark%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (5, N'Sweet Vermouth', N'https://www.thecocktaildb.com/images/ingredients/Sweet%20Vermouth.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (6, N'Strawberry schnapps', N'https://www.thecocktaildb.com/images/ingredients/Strawberry%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (7, N'Scotch', N'https://www.thecocktaildb.com/images/ingredients/Scotch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (8, N'Apricot brandy', N'https://www.thecocktaildb.com/images/ingredients/Apricot%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (9, N'Triple sec', N'https://www.thecocktaildb.com/images/ingredients/Triple%20sec.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (10, N'Southern Comfort', N'https://www.thecocktaildb.com/images/ingredients/Southern%20Comfort.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (11, N'Orange bitters', N'https://www.thecocktaildb.com/images/ingredients/Orange%20bitters.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (12, N'Brandy', N'https://www.thecocktaildb.com/images/ingredients/Brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (13, N'Lemon vodka', N'https://www.thecocktaildb.com/images/ingredients/Lemon%20vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (14, N'Blended whiskey', N'https://www.thecocktaildb.com/images/ingredients/Blended%20whiskey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (15, N'Dry Vermouth', N'https://www.thecocktaildb.com/images/ingredients/Dry%20Vermouth.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (16, N'Amaretto', N'https://www.thecocktaildb.com/images/ingredients/Amaretto.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (17, N'Tea', N'https://www.thecocktaildb.com/images/ingredients/Tea.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (18, N'Champagne', N'https://www.thecocktaildb.com/images/ingredients/Champagne.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (19, N'Coffee liqueur', N'https://www.thecocktaildb.com/images/ingredients/Coffee%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (20, N'Bourbon', N'https://thecocktaildb.com/images/ingredients/Bourbon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (21, N'Tequila', N'https://thecocktaildb.com/images/ingredients/Tequila.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (22, N'Vodka', N'https://thecocktaildb.com/images/ingredients/Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (23, N'Anejo rum', N'https://thecocktaildb.com/images/ingredients/Aejo%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (24, N'Bitters', N'https://thecocktaildb.com/images/ingredients/Bitters.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (25, N'Sugar', N'https://thecocktaildb.com/images/ingredients/Sugar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (26, N'Kahlua', N'https://thecocktaildb.com/images/ingredients/Kahlua.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (27, N'demerara Sugar', N'https://thecocktaildb.com/images/ingredients/demerara%20Sugar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (28, N'Dubonnet Rouge', N'https://thecocktaildb.com/images/ingredients/Dubonnet%20Rouge.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (29, N'Lime juice', N'https://thecocktaildb.com/images/ingredients/Lime%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (30, N'Irish whiskey', N'https://thecocktaildb.com/images/ingredients/Irish%20whiskey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (31, N'Apple brandy', N'https://thecocktaildb.com/images/ingredients/Apple%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (32, N'Carbonated water', N'https://thecocktaildb.com/images/ingredients/Carbonated%20water.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (33, N'Cherry brandy', N'https://thecocktaildb.com/images/ingredients/Cherry%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (34, N'Creme de Cacao', N'https://thecocktaildb.com/images/ingredients/Creme%20de%20Cacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (35, N'Grenadine', N'https://thecocktaildb.com/images/ingredients/Grenadine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (36, N'Port', N'https://thecocktaildb.com/images/ingredients/Port.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (37, N'Coffee brandy', N'https://thecocktaildb.com/images/ingredients/Coffee%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (38, N'Red wine', N'https://thecocktaildb.com/images/ingredients/Red%20wine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (39, N'Rum', N'https://thecocktaildb.com/images/ingredients/Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (40, N'Grapefruit juice', N'https://thecocktaildb.com/images/ingredients/Grapefruit%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (41, N'Ricard', N'https://thecocktaildb.com/images/ingredients/Ricard.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (42, N'Sherry', N'https://thecocktaildb.com/images/ingredients/Sherry.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (43, N'Cognac', N'https://thecocktaildb.com/images/ingredients/Cognac.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (44, N'Sloe gin', N'https://thecocktaildb.com/images/ingredients/Sloe%20gin.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (45, N'Apple juice', N'https://thecocktaildb.com/images/ingredients/Apple%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (46, N'Pineapple juice', N'https://thecocktaildb.com/images/ingredients/Pineapple%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (47, N'Lemon juice', N'https://thecocktaildb.com/images/ingredients/Lemon%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (48, N'Sugar syrup', N'https://thecocktaildb.com/images/ingredients/Sugar%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (49, N'Milk', N'https://thecocktaildb.com/images/ingredients/Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (50, N'Strawberries', N'https://thecocktaildb.com/images/ingredients/Strawberries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (51, N'Chocolate syrup', N'https://thecocktaildb.com/images/ingredients/Chocolate%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (52, N'Yoghurt', N'https://thecocktaildb.com/images/ingredients/Yoghurt.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (53, N'Mango', N'https://thecocktaildb.com/images/ingredients/Mango.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (54, N'Ginger', N'https://thecocktaildb.com/images/ingredients/Ginger.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (55, N'Lime', N'https://thecocktaildb.com/images/ingredients/Lime.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (56, N'Cantaloupe', N'https://thecocktaildb.com/images/ingredients/Cantaloupe.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (57, N'Berries', N'https://thecocktaildb.com/images/ingredients/Berries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (58, N'Grapes', N'https://thecocktaildb.com/images/ingredients/Grapes.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (59, N'Kiwi', N'https://thecocktaildb.com/images/ingredients/Kiwi.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (60, N'Tomato juice', N'https://thecocktaildb.com/images/ingredients/Tomato%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (61, N'Cocoa powder', N'https://thecocktaildb.com/images/ingredients/Cocoa%20powder.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (62, N'Chocolate', N'https://thecocktaildb.com/images/ingredients/Chocolate.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (63, N'Heavy cream', N'https://thecocktaildb.com/images/ingredients/Heavy%20cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (64, N'Galliano', N'https://thecocktaildb.com/images/ingredients/Galliano.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (65, N'Peach Vodka', N'https://thecocktaildb.com/images/ingredients/Peach%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (66, N'Ouzo', N'https://thecocktaildb.com/images/ingredients/Ouzo.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (67, N'Coffee', N'https://thecocktaildb.com/images/ingredients/Coffee.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (68, N'Spiced rum', N'https://thecocktaildb.com/images/ingredients/Spiced%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (69, N'Water', N'https://thecocktaildb.com/images/ingredients/Water.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (70, N'Espresso', N'https://thecocktaildb.com/images/ingredients/Espresso.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (71, N'Angelica root', N'https://thecocktaildb.com/images/ingredients/Angelica%20root.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (72, N'Orange', N'https://thecocktaildb.com/images/ingredients/Orange.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (73, N'Cranberries', N'https://thecocktaildb.com/images/ingredients/Cranberries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (74, N'Johnnie Walker', N'https://thecocktaildb.com/images/ingredients/Johnnie%20Walker.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (75, N'Apple cider', N'https://thecocktaildb.com/images/ingredients/Apple%20cider.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (76, N'Everclear', N'https://thecocktaildb.com/images/ingredients/Everclear.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (77, N'Cranberry juice', N'https://thecocktaildb.com/images/ingredients/Cranberry%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (78, N'Egg yolk', N'https://thecocktaildb.com/images/ingredients/Egg%20yolk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (79, N'Egg', N'https://thecocktaildb.com/images/ingredients/Egg.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (80, N'Grape juice', N'https://thecocktaildb.com/images/ingredients/Grape%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (81, N'Peach nectar', N'https://thecocktaildb.com/images/ingredients/Peach%20nectar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (82, N'Lemon', N'https://thecocktaildb.com/images/ingredients/Lemon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (83, N'Firewater', N'https://thecocktaildb.com/images/ingredients/Firewater.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (84, N'Lemonade', N'https://thecocktaildb.com/images/ingredients/Lemonade.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (85, N'Lager', N'https://thecocktaildb.com/images/ingredients/Lager.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (86, N'Whiskey', N'https://thecocktaildb.com/images/ingredients/Whiskey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (87, N'Absolut Citron', N'https://thecocktaildb.com/images/ingredients/Absolut%20Citron.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (88, N'Pisco', N'https://thecocktaildb.com/images/ingredients/Pisco.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (89, N'Irish cream', N'https://thecocktaildb.com/images/ingredients/Irish%20cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (90, N'Ale', N'https://thecocktaildb.com/images/ingredients/Ale.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (91, N'Chocolate liqueur', N'https://thecocktaildb.com/images/ingredients/Chocolate%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (92, N'Midori melon liqueur', N'https://thecocktaildb.com/images/ingredients/Midori%20melon%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (93, N'Sambuca', N'https://thecocktaildb.com/images/ingredients/Sambuca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (94, N'Cider', N'https://thecocktaildb.com/images/ingredients/Cider.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (95, N'Sprite', N'https://thecocktaildb.com/images/ingredients/Sprite.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (96, N'7-Up', N'https://thecocktaildb.com/images/ingredients/7-Up.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (97, N'Blackberry brandy', N'https://thecocktaildb.com/images/ingredients/Blackberry%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (98, N'Peppermint schnapps', N'https://thecocktaildb.com/images/ingredients/Peppermint%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (99, N'Creme de Cassis', N'https://thecocktaildb.com/images/ingredients/Creme%20de%20Cassis.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (100, N'Jack Daniels', N'https://thecocktaildb.com/images/ingredients/Jack%20Daniels.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (101, N'Mint', N'https://thecocktaildb.com/images/ingredients/Mint.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (102, N'Maraschino Cherry', N'https://thecocktaildb.com/images/ingredients/Maraschino%20Cherry.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (103, N'Lemon Peel', N'https://thecocktaildb.com/images/ingredients/Lemon%20Peel.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (104, N'Wormwood', N'https://thecocktaildb.com/images/ingredients/Wormwood.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (105, N'Ice', N'https://thecocktaildb.com/images/ingredients/Ice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (106, N'Jelly', N'https://thecocktaildb.com/images/ingredients/Jelly.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (107, N'Absolut Kurant', N'https://thecocktaildb.com/images/ingredients/Absolut%20Kurant.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (108, N'Absolut Peppar', N'https://thecocktaildb.com/images/ingredients/Absolut%20Peppar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (109, N'Absolut Vodka', N'https://thecocktaildb.com/images/ingredients/Absolut%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (110, N'Advocaat', N'https://thecocktaildb.com/images/ingredients/Advocaat.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (111, N'Aftershock', N'https://thecocktaildb.com/images/ingredients/Aftershock.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (112, N'Agave Syrup', N'https://thecocktaildb.com/images/ingredients/Agave%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (113, N'Allspice', N'https://thecocktaildb.com/images/ingredients/Allspice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (114, N'Almond Extract', N'https://thecocktaildb.com/images/ingredients/Almond%20Extract.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (115, N'Almond Flavoring', N'https://thecocktaildb.com/images/ingredients/Almond%20Flavoring.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (116, N'Almond', N'https://thecocktaildb.com/images/ingredients/Almond.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (117, N'Angostura Bitters', N'https://thecocktaildb.com/images/ingredients/Angostura%20Bitters.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (118, N'Anis', N'https://thecocktaildb.com/images/ingredients/Anis.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (119, N'Anise', N'https://thecocktaildb.com/images/ingredients/Anise.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (120, N'Anisette', N'https://thecocktaildb.com/images/ingredients/Anisette.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (121, N'Aperol', N'https://thecocktaildb.com/images/ingredients/Aperol.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (122, N'Apfelkorn', N'https://thecocktaildb.com/images/ingredients/Apfelkorn.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (123, N'Apple Schnapps', N'https://thecocktaildb.com/images/ingredients/Apple%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (124, N'Apple', N'https://thecocktaildb.com/images/ingredients/Apple.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (125, N'Apricot Nectar', N'https://thecocktaildb.com/images/ingredients/Apricot%20Nectar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (126, N'Apricot', N'https://thecocktaildb.com/images/ingredients/Apricot.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (127, N'Aquavit', N'https://thecocktaildb.com/images/ingredients/Aquavit.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (128, N'Asafoetida', N'https://thecocktaildb.com/images/ingredients/Asafoetida.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (129, N'Bacardi Limon', N'https://thecocktaildb.com/images/ingredients/Bacardi%20Limon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (130, N'Bacardi', N'https://thecocktaildb.com/images/ingredients/Bacardi.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (131, N'Baileys Irish Cream', N'https://thecocktaildb.com/images/ingredients/Baileys%20Irish%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (132, N'Banana Liqueur', N'https://thecocktaildb.com/images/ingredients/Banana%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (133, N'Banana Rum', N'https://thecocktaildb.com/images/ingredients/Banana%20Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (134, N'Banana Syrup', N'https://thecocktaildb.com/images/ingredients/Banana%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (135, N'Banana', N'https://thecocktaildb.com/images/ingredients/Banana.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (136, N'Barenjager', N'https://thecocktaildb.com/images/ingredients/Barenjager.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (137, N'Basil', N'https://thecocktaildb.com/images/ingredients/Basil.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (138, N'Beef Stock', N'https://thecocktaildb.com/images/ingredients/Beef%20Stock.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (139, N'Beer', N'https://thecocktaildb.com/images/ingredients/Beer.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (140, N'Benedictine', N'https://thecocktaildb.com/images/ingredients/Benedictine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (141, N'Bitter lemon', N'https://thecocktaildb.com/images/ingredients/Bitter%20lemon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (142, N'Black Pepper', N'https://thecocktaildb.com/images/ingredients/Black%20Pepper.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (143, N'Black Rum', N'https://thecocktaildb.com/images/ingredients/Black%20Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (144, N'Black Sambuca', N'https://thecocktaildb.com/images/ingredients/Black%20Sambuca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (145, N'Blackberries', N'https://thecocktaildb.com/images/ingredients/Blackberries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (146, N'Blackberry Schnapps', N'https://thecocktaildb.com/images/ingredients/Blackberry%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (147, N'Blackcurrant Cordial', N'https://thecocktaildb.com/images/ingredients/Blackcurrant%20Cordial.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (148, N'Blackcurrant Schnapps', N'https://thecocktaildb.com/images/ingredients/Blackcurrant%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (149, N'Blackcurrant Squash', N'https://thecocktaildb.com/images/ingredients/Blackcurrant%20Squash.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (150, N'Blue Curacao', N'https://thecocktaildb.com/images/ingredients/Blue%20Curacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (151, N'Blue Maui', N'https://thecocktaildb.com/images/ingredients/Blue%20Maui.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (152, N'Blueberries', N'https://thecocktaildb.com/images/ingredients/Blueberries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (153, N'Blueberry Schnapps', N'https://thecocktaildb.com/images/ingredients/Blueberry%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (154, N'Brown Sugar', N'https://thecocktaildb.com/images/ingredients/Brown%20Sugar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (155, N'Butter', N'https://thecocktaildb.com/images/ingredients/Butter.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (156, N'Butterscotch Schnapps', N'https://thecocktaildb.com/images/ingredients/Butterscotch%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (157, N'Cachaca', N'https://thecocktaildb.com/images/ingredients/Cachaca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (158, N'Calvados', N'https://thecocktaildb.com/images/ingredients/Calvados.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (159, N'Campari', N'https://thecocktaildb.com/images/ingredients/Campari.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (160, N'Canadian Whisky', N'https://thecocktaildb.com/images/ingredients/Canadian%20Whisky.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (161, N'Candy', N'https://thecocktaildb.com/images/ingredients/Candy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (162, N'Caramel Coloring', N'https://thecocktaildb.com/images/ingredients/Caramel%20Coloring.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (163, N'Carbonated Soft Drink', N'https://thecocktaildb.com/images/ingredients/Carbonated%20Soft%20Drink.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (164, N'Cardamom', N'https://thecocktaildb.com/images/ingredients/Cardamom.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (165, N'Cayenne Pepper', N'https://thecocktaildb.com/images/ingredients/Cayenne%20Pepper.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (166, N'Celery Salt', N'https://thecocktaildb.com/images/ingredients/Celery%20Salt.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (167, N'Celery', N'https://thecocktaildb.com/images/ingredients/Celery.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (168, N'Chambord Raspberry Liqueur', N'https://thecocktaildb.com/images/ingredients/Chambord%20Raspberry%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (169, N'Cherries', N'https://thecocktaildb.com/images/ingredients/Cherries.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (170, N'Cherry Cola', N'https://thecocktaildb.com/images/ingredients/Cherry%20Cola.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (171, N'Cherry Grenadine', N'https://thecocktaildb.com/images/ingredients/Cherry%20Grenadine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (172, N'Cherry Heering', N'https://thecocktaildb.com/images/ingredients/Cherry%20Heering.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (173, N'Cherry Juice', N'https://thecocktaildb.com/images/ingredients/Cherry%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (174, N'Cherry Liqueur', N'https://thecocktaildb.com/images/ingredients/Cherry%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (175, N'Cherry', N'https://thecocktaildb.com/images/ingredients/Cherry.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (176, N'Chocolate Ice-cream', N'https://thecocktaildb.com/images/ingredients/Chocolate%20Ice-cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (177, N'Chocolate Milk', N'https://thecocktaildb.com/images/ingredients/Chocolate%20Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (178, N'Cinnamon Schnapps', N'https://thecocktaildb.com/images/ingredients/Cinnamon%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (179, N'Cinnamon', N'https://thecocktaildb.com/images/ingredients/Cinnamon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (180, N'Citrus Vodka', N'https://thecocktaildb.com/images/ingredients/Citrus%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (181, N'Clamato Juice', N'https://thecocktaildb.com/images/ingredients/Clamato%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (182, N'Cloves', N'https://thecocktaildb.com/images/ingredients/Cloves.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (183, N'Club Soda', N'https://thecocktaildb.com/images/ingredients/Club%20Soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (184, N'Coca-Cola', N'https://thecocktaildb.com/images/ingredients/Coca-Cola.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (185, N'Cocktail Onion', N'https://thecocktaildb.com/images/ingredients/Cocktail%20Onion.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (186, N'Coconut Cream', N'https://thecocktaildb.com/images/ingredients/Coconut%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (187, N'Coconut Liqueur', N'https://thecocktaildb.com/images/ingredients/Coconut%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (188, N'Coconut Milk', N'https://thecocktaildb.com/images/ingredients/Coconut%20Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (189, N'Coconut Rum', N'https://thecocktaildb.com/images/ingredients/Coconut%20Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (190, N'Coconut Syrup', N'https://thecocktaildb.com/images/ingredients/Coconut%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (191, N'Cointreau', N'https://thecocktaildb.com/images/ingredients/Cointreau.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (192, N'Cola', N'https://thecocktaildb.com/images/ingredients/Cola.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (193, N'Cold Water', N'https://thecocktaildb.com/images/ingredients/Cold%20Water.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (194, N'Condensed Milk', N'https://thecocktaildb.com/images/ingredients/Condensed%20Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (195, N'Coriander', N'https://thecocktaildb.com/images/ingredients/Coriander.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (196, N'Corn Syrup', N'https://thecocktaildb.com/images/ingredients/Corn%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (197, N'Cornstarch', N'https://thecocktaildb.com/images/ingredients/Cornstarch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (198, N'Corona', N'https://thecocktaildb.com/images/ingredients/Corona.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (199, N'Cranberry Liqueur', N'https://thecocktaildb.com/images/ingredients/Cranberry%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (201, N'Cranberry Vodka', N'https://thecocktaildb.com/images/ingredients/Cranberry%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (202, N'Cream of Coconut', N'https://thecocktaildb.com/images/ingredients/Cream%20of%20Coconut.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (203, N'Cream Sherry', N'https://thecocktaildb.com/images/ingredients/Cream%20Sherry.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (204, N'Cream Soda', N'https://thecocktaildb.com/images/ingredients/Cream%20Soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (205, N'Cream', N'https://thecocktaildb.com/images/ingredients/Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (206, N'Creme De Almond', N'https://thecocktaildb.com/images/ingredients/Creme%20De%20Almond.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (207, N'Creme De Banane', N'https://thecocktaildb.com/images/ingredients/Creme%20De%20Banane.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (208, N'Creme De Noyaux', N'https://thecocktaildb.com/images/ingredients/Creme%20De%20Noyaux.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (209, N'Creme Fraiche', N'https://thecocktaildb.com/images/ingredients/Creme%20Fraiche.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (210, N'Crown Royal', N'https://thecocktaildb.com/images/ingredients/Crown%20Royal.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (211, N'Crystal Light', N'https://thecocktaildb.com/images/ingredients/Crystal%20Light.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (212, N'Cucumber', N'https://thecocktaildb.com/images/ingredients/Cucumber.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (213, N'Cumin Powder', N'https://thecocktaildb.com/images/ingredients/Cumin%20Powder.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (214, N'Cumin Seed', N'https://thecocktaildb.com/images/ingredients/Cumin%20Seed.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (215, N'Curacao', N'https://thecocktaildb.com/images/ingredients/Curacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (216, N'Cynar', N'https://thecocktaildb.com/images/ingredients/Cynar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (217, N'Daiquiri Mix', N'https://thecocktaildb.com/images/ingredients/Daiquiri%20Mix.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (218, N'Dark Chocolate', N'https://thecocktaildb.com/images/ingredients/Dark%20Chocolate.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (219, N'Dark Creme De Cacao', N'https://thecocktaildb.com/images/ingredients/Dark%20Creme%20De%20Cacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (220, N'Dark Soy Sauce', N'https://thecocktaildb.com/images/ingredients/Dark%20Soy%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (221, N'Dr. Pepper', N'https://thecocktaildb.com/images/ingredients/Dr.%20Pepper.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (222, N'Drambuie', N'https://thecocktaildb.com/images/ingredients/Drambuie.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (223, N'Dried Oregano', N'https://thecocktaildb.com/images/ingredients/Dried%20Oregano.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (224, N'Dubonnet Blanc', N'https://thecocktaildb.com/images/ingredients/Dubonnet%20Blanc.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (225, N'Egg White', N'https://thecocktaildb.com/images/ingredients/Egg%20White.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (226, N'Eggnog', N'https://thecocktaildb.com/images/ingredients/Eggnog.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (227, N'Erin Cream', N'https://thecocktaildb.com/images/ingredients/Erin%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (228, N'Fanta', N'https://thecocktaildb.com/images/ingredients/Fanta.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (229, N'Fennel Seeds', N'https://thecocktaildb.com/images/ingredients/Fennel%20Seeds.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (230, N'Flaked Almonds', N'https://thecocktaildb.com/images/ingredients/Flaked%20Almonds.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (231, N'Food Coloring', N'https://thecocktaildb.com/images/ingredients/Food%20Coloring.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (232, N'Forbidden Fruit', N'https://thecocktaildb.com/images/ingredients/Forbidden%20Fruit.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (233, N'Frangelico', N'https://thecocktaildb.com/images/ingredients/Frangelico.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (234, N'Fresca', N'https://thecocktaildb.com/images/ingredients/Fresca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (235, N'Fresh Basil', N'https://thecocktaildb.com/images/ingredients/Fresh%20Basil.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (236, N'Fresh Lemon Juice', N'https://thecocktaildb.com/images/ingredients/Fresh%20Lemon%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (237, N'Fruit Juice', N'https://thecocktaildb.com/images/ingredients/Fruit%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (238, N'Fruit Punch', N'https://thecocktaildb.com/images/ingredients/Fruit%20Punch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (239, N'Fruit', N'https://thecocktaildb.com/images/ingredients/Fruit.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (240, N'Garlic Sauce', N'https://thecocktaildb.com/images/ingredients/Garlic%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (241, N'Gatorade', N'https://thecocktaildb.com/images/ingredients/Gatorade.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (242, N'Ginger Ale', N'https://thecocktaildb.com/images/ingredients/Ginger%20Ale.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (243, N'Ginger Beer', N'https://thecocktaildb.com/images/ingredients/Ginger%20Beer.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (244, N'Glycerine', N'https://thecocktaildb.com/images/ingredients/Glycerine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (245, N'Godiva Liqueur', N'https://thecocktaildb.com/images/ingredients/Godiva%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (246, N'Gold rum', N'https://thecocktaildb.com/images/ingredients/Gold%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (247, N'Gold Tequila', N'https://thecocktaildb.com/images/ingredients/Gold%20Tequila.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (248, N'Goldschlager', N'https://thecocktaildb.com/images/ingredients/Goldschlager.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (249, N'Grain Alcohol', N'https://thecocktaildb.com/images/ingredients/Grain%20Alcohol.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (250, N'Grand Marnier', N'https://thecocktaildb.com/images/ingredients/Grand%20Marnier.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (251, N'Granulated Sugar', N'https://thecocktaildb.com/images/ingredients/Granulated%20Sugar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (252, N'Grape soda', N'https://thecocktaildb.com/images/ingredients/Grape%20soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (253, N'Green Chartreuse', N'https://thecocktaildb.com/images/ingredients/Green%20Chartreuse.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (254, N'Green Creme de Menthe', N'https://thecocktaildb.com/images/ingredients/Green%20Creme%20de%20Menthe.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (255, N'Green Ginger Wine', N'https://thecocktaildb.com/images/ingredients/Green%20Ginger%20Wine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (256, N'Green Olives', N'https://thecocktaildb.com/images/ingredients/Green%20Olives.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (257, N'Ground Ginger', N'https://thecocktaildb.com/images/ingredients/Ground%20Ginger.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (258, N'Guava juice', N'https://thecocktaildb.com/images/ingredients/Guava%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (259, N'Guinness stout', N'https://thecocktaildb.com/images/ingredients/Guinness%20stout.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (260, N'Guinness', N'https://thecocktaildb.com/images/ingredients/Guinness.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (261, N'Half-and-half', N'https://thecocktaildb.com/images/ingredients/Half-and-half.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (262, N'Hawaiian punch', N'https://thecocktaildb.com/images/ingredients/Hawaiian%20punch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (263, N'Hazelnut liqueur', N'https://thecocktaildb.com/images/ingredients/Hazelnut%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (264, N'Honey', N'https://thecocktaildb.com/images/ingredients/Honey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (265, N'Hooch', N'https://thecocktaildb.com/images/ingredients/Hooch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (266, N'Hot Chocolate', N'https://thecocktaildb.com/images/ingredients/Hot%20Chocolate.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (267, N'Hot Damn', N'https://thecocktaildb.com/images/ingredients/Hot%20Damn.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (268, N'Hot Sauce', N'https://thecocktaildb.com/images/ingredients/Hot%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (269, N'Hpnotiq', N'https://thecocktaildb.com/images/ingredients/Hpnotiq.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (270, N'Ice-Cream', N'https://thecocktaildb.com/images/ingredients/Ice-Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (271, N'Iced tea', N'https://thecocktaildb.com/images/ingredients/Iced%20tea.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (272, N'Jello', N'https://thecocktaildb.com/images/ingredients/Jello.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (273, N'Jagermeister', N'https://thecocktaildb.com/images/ingredients/Jagermeister.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (274, N'Jim Beam', N'https://thecocktaildb.com/images/ingredients/Jim%20Beam.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (275, N'Key Largo Schnapps', N'https://thecocktaildb.com/images/ingredients/Key%20Largo%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (276, N'Kirschwasser', N'https://thecocktaildb.com/images/ingredients/Kirschwasser.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (277, N'Kiwi liqueur', N'https://thecocktaildb.com/images/ingredients/Kiwi%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (278, N'Kool-Aid', N'https://thecocktaildb.com/images/ingredients/Kool-Aid.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (279, N'Kummel', N'https://thecocktaildb.com/images/ingredients/Kummel.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (280, N'Lemon soda', N'https://thecocktaildb.com/images/ingredients/Lemon%20soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (281, N'Lemon-lime soda', N'https://thecocktaildb.com/images/ingredients/Lemon-lime%20soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (282, N'lemon-lime', N'https://thecocktaildb.com/images/ingredients/lemon-lime.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (283, N'lemon', N'https://thecocktaildb.com/images/ingredients/lemon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (284, N'Licorice Root', N'https://thecocktaildb.com/images/ingredients/Licorice%20Root.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (285, N'Light Cream', N'https://thecocktaildb.com/images/ingredients/Light%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (286, N'Lillet', N'https://thecocktaildb.com/images/ingredients/Lillet.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (287, N'Lime juice cordial', N'https://thecocktaildb.com/images/ingredients/Lime%20juice%20cordial.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (288, N'Lime liqueur', N'https://thecocktaildb.com/images/ingredients/Lime%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (289, N'Lime Peel', N'https://thecocktaildb.com/images/ingredients/Lime%20Peel.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (290, N'Lime vodka', N'https://thecocktaildb.com/images/ingredients/Lime%20vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (291, N'Limeade', N'https://thecocktaildb.com/images/ingredients/Limeade.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (292, N'Madeira', N'https://thecocktaildb.com/images/ingredients/Madeira.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (293, N'Malibu Rum', N'https://thecocktaildb.com/images/ingredients/Malibu%20Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (294, N'Mandarin', N'https://thecocktaildb.com/images/ingredients/Mandarin.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (295, N'Mandarine napoleon', N'https://thecocktaildb.com/images/ingredients/Mandarine%20napoleon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (296, N'Maple syrup', N'https://thecocktaildb.com/images/ingredients/Maple%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (297, N'Maraschino cherry juice', N'https://thecocktaildb.com/images/ingredients/Maraschino%20cherry%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (298, N'Maraschino Liqueur', N'https://thecocktaildb.com/images/ingredients/Maraschino%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (299, N'Margarita mix', N'https://thecocktaildb.com/images/ingredients/Margarita%20mix.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (300, N'Marjoram leaves', N'https://thecocktaildb.com/images/ingredients/Marjoram%20leaves.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (301, N'Marshmallows', N'https://thecocktaildb.com/images/ingredients/Marshmallows.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (302, N'Maui', N'https://thecocktaildb.com/images/ingredients/Maui.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (303, N'Melon Liqueur', N'https://thecocktaildb.com/images/ingredients/Melon%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (304, N'Melon Vodka', N'https://thecocktaildb.com/images/ingredients/Melon%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (305, N'Mezcal', N'https://thecocktaildb.com/images/ingredients/Mezcal.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (306, N'Midori', N'https://thecocktaildb.com/images/ingredients/Midori.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (307, N'Mint syrup', N'https://thecocktaildb.com/images/ingredients/Mint%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (308, N'Mountain Dew', N'https://thecocktaildb.com/images/ingredients/Mountain%20Dew.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (309, N'Nutmeg', N'https://thecocktaildb.com/images/ingredients/Nutmeg.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (310, N'Olive Oil', N'https://thecocktaildb.com/images/ingredients/Olive%20Oil.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (311, N'Olive', N'https://thecocktaildb.com/images/ingredients/Olive.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (312, N'Onion', N'https://thecocktaildb.com/images/ingredients/Onion.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (313, N'Orange Curacao', N'https://thecocktaildb.com/images/ingredients/Orange%20Curacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (314, N'Orange Juice', N'https://thecocktaildb.com/images/ingredients/Orange%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (315, N'Orange liqueur', N'https://thecocktaildb.com/images/ingredients/Orange%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (316, N'Orange Peel', N'https://thecocktaildb.com/images/ingredients/Orange%20Peel.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (317, N'Orange rum', N'https://thecocktaildb.com/images/ingredients/Orange%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (318, N'Orange Soda', N'https://thecocktaildb.com/images/ingredients/Orange%20Soda.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (319, N'Orange spiral', N'https://thecocktaildb.com/images/ingredients/Orange%20spiral.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (320, N'Orange vodka', N'https://thecocktaildb.com/images/ingredients/Orange%20vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (321, N'Oreo cookie', N'https://thecocktaildb.com/images/ingredients/Oreo%20cookie.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (322, N'Orgeat Syrup', N'https://thecocktaildb.com/images/ingredients/Orgeat%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (323, N'Oyster Sauce', N'https://thecocktaildb.com/images/ingredients/Oyster%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (324, N'Papaya juice', N'https://thecocktaildb.com/images/ingredients/Papaya%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (325, N'Papaya', N'https://thecocktaildb.com/images/ingredients/Papaya.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (326, N'Parfait amour', N'https://thecocktaildb.com/images/ingredients/Parfait%20amour.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (327, N'Passion fruit juice', N'https://thecocktaildb.com/images/ingredients/Passion%20fruit%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (328, N'Passion fruit syrup', N'https://thecocktaildb.com/images/ingredients/Passion%20fruit%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (329, N'Passoa', N'https://thecocktaildb.com/images/ingredients/Passoa.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (330, N'Peach brandy', N'https://thecocktaildb.com/images/ingredients/Peach%20brandy.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (331, N'Peach juice', N'https://thecocktaildb.com/images/ingredients/Peach%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (332, N'Peach liqueur', N'https://thecocktaildb.com/images/ingredients/Peach%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (333, N'Peach Schnapps', N'https://thecocktaildb.com/images/ingredients/Peach%20Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (334, N'Peach', N'https://thecocktaildb.com/images/ingredients/Peach.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (335, N'Peachtree schnapps', N'https://thecocktaildb.com/images/ingredients/Peachtree%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (336, N'Peanut Oil', N'https://thecocktaildb.com/images/ingredients/Peanut%20Oil.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (337, N'Pepper', N'https://thecocktaildb.com/images/ingredients/Pepper.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (338, N'Peppermint extract', N'https://thecocktaildb.com/images/ingredients/Peppermint%20extract.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (339, N'Pepsi Cola', N'https://thecocktaildb.com/images/ingredients/Pepsi%20Cola.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (340, N'Pernod', N'https://thecocktaildb.com/images/ingredients/Pernod.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (341, N'Peychaud bitters', N'https://thecocktaildb.com/images/ingredients/Peychaud%20bitters.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (342, N'Pina colada mix', N'https://thecocktaildb.com/images/ingredients/Pina%20colada%20mix.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (343, N'Pineapple rum', N'https://thecocktaildb.com/images/ingredients/Pineapple%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (344, N'Pineapple vodka', N'https://thecocktaildb.com/images/ingredients/Pineapple%20vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (345, N'Pineapple-orange-banana juice', N'https://thecocktaildb.com/images/ingredients/Pineapple-orange-banana%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (346, N'Pineapple', N'https://thecocktaildb.com/images/ingredients/Pineapple.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (347, N'Pink lemonade', N'https://thecocktaildb.com/images/ingredients/Pink%20lemonade.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (348, N'Pisang Ambon', N'https://thecocktaildb.com/images/ingredients/Pisang%20Ambon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (349, N'Plain Chocolate', N'https://thecocktaildb.com/images/ingredients/Plain%20Chocolate.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (350, N'Plain Flour', N'https://thecocktaildb.com/images/ingredients/Plain%20Flour.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (351, N'Plums', N'https://thecocktaildb.com/images/ingredients/Plums.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (352, N'Powdered Sugar', N'https://thecocktaildb.com/images/ingredients/Powdered%20Sugar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (353, N'Purple passion', N'https://thecocktaildb.com/images/ingredients/Purple%20passion.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (354, N'Raisins', N'https://thecocktaildb.com/images/ingredients/Raisins.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (355, N'Raspberry cordial', N'https://thecocktaildb.com/images/ingredients/Raspberry%20cordial.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (356, N'Raspberry Jam', N'https://thecocktaildb.com/images/ingredients/Raspberry%20Jam.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (357, N'Raspberry Juice', N'https://thecocktaildb.com/images/ingredients/Raspberry%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (358, N'Raspberry Liqueur', N'https://thecocktaildb.com/images/ingredients/Raspberry%20Liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (359, N'Raspberry schnapps', N'https://thecocktaildb.com/images/ingredients/Raspberry%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (360, N'Raspberry syrup', N'https://thecocktaildb.com/images/ingredients/Raspberry%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (361, N'Raspberry Vodka', N'https://thecocktaildb.com/images/ingredients/Raspberry%20Vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (362, N'Red Chile Flakes', N'https://thecocktaildb.com/images/ingredients/Red%20Chile%20Flakes.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (363, N'Red Chili Flakes', N'https://thecocktaildb.com/images/ingredients/Red%20Chili%20Flakes.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (364, N'Red Hot Chili Flakes', N'https://thecocktaildb.com/images/ingredients/Red%20Hot%20Chili%20Flakes.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (365, N'Rhubarb', N'https://thecocktaildb.com/images/ingredients/Rhubarb.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (366, N'Rock Salt', N'https://thecocktaildb.com/images/ingredients/Rock%20Salt.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (367, N'Root beer schnapps', N'https://thecocktaildb.com/images/ingredients/Root%20beer%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (368, N'Root beer', N'https://thecocktaildb.com/images/ingredients/Root%20beer.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (369, N'Roses sweetened lime juice', N'https://thecocktaildb.com/images/ingredients/Roses%20sweetened%20lime%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (370, N'Rosewater', N'https://thecocktaildb.com/images/ingredients/Rosewater.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (371, N'Rumple Minze', N'https://thecocktaildb.com/images/ingredients/Rumple%20Minze.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (372, N'Rye Whiskey', N'https://thecocktaildb.com/images/ingredients/Rye%20Whiskey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (373, N'Sake', N'https://thecocktaildb.com/images/ingredients/Sake.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (374, N'Salt', N'https://thecocktaildb.com/images/ingredients/Salt.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (375, N'Sarsaparilla', N'https://thecocktaildb.com/images/ingredients/Sarsaparilla.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (376, N'Schnapps', N'https://thecocktaildb.com/images/ingredients/Schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (377, N'Schweppes Lemon', N'https://thecocktaildb.com/images/ingredients/Schweppes%20Lemon.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (378, N'Schweppes Russchian', N'https://thecocktaildb.com/images/ingredients/Schweppes%20Russchian.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (379, N'Sherbet', N'https://thecocktaildb.com/images/ingredients/Sherbet.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (380, N'Sirup of roses', N'https://thecocktaildb.com/images/ingredients/Sirup%20of%20roses.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (381, N'Soda Water', N'https://thecocktaildb.com/images/ingredients/Soda%20Water.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (382, N'Sour Apple Pucker', N'https://thecocktaildb.com/images/ingredients/Sour%20Apple%20Pucker.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (383, N'Sour Mix', N'https://thecocktaildb.com/images/ingredients/Sour%20Mix.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (384, N'Soy Milk', N'https://thecocktaildb.com/images/ingredients/Soy%20Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (385, N'Soy Sauce', N'https://thecocktaildb.com/images/ingredients/Soy%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (386, N'Soya Milk', N'https://thecocktaildb.com/images/ingredients/Soya%20Milk.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (387, N'Soya Sauce', N'https://thecocktaildb.com/images/ingredients/Soya%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (388, N'Squeezed Orange', N'https://thecocktaildb.com/images/ingredients/Squeezed%20Orange.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (389, N'Squirt', N'https://thecocktaildb.com/images/ingredients/Squirt.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (390, N'Strawberry juice', N'https://thecocktaildb.com/images/ingredients/Strawberry%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (391, N'Tennessee whiskey', N'https://thecocktaildb.com/images/ingredients/Tennessee%20whiskey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (392, N'Tequila rose', N'https://thecocktaildb.com/images/ingredients/Tequila%20rose.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (393, N'Tia Maria', N'https://thecocktaildb.com/images/ingredients/Tia%20Maria.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (394, N'Tomato', N'https://thecocktaildb.com/images/ingredients/Tomato.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (395, N'Tonic Water', N'https://thecocktaildb.com/images/ingredients/Tonic%20Water.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (396, N'Tropicana', N'https://thecocktaildb.com/images/ingredients/Tropicana.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (397, N'Tuaca', N'https://thecocktaildb.com/images/ingredients/Tuaca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (398, N'Strawberry juice', N'https://thecocktaildb.com/images/ingredients/Strawberry%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (399, N'Strawberry liqueur', N'https://thecocktaildb.com/images/ingredients/Strawberry%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (400, N'Strawberry syrup', N'https://thecocktaildb.com/images/ingredients/Strawberry%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (401, N'Sunny delight', N'https://thecocktaildb.com/images/ingredients/Sunny%20delight.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (402, N'Surge', N'https://thecocktaildb.com/images/ingredients/Surge.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (403, N'Swedish punsch', N'https://thecocktaildb.com/images/ingredients/Swedish%20punsch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (404, N'Sweet and Sour', N'https://thecocktaildb.com/images/ingredients/Sweet%20and%20Sour.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (405, N'Sweet Cream', N'https://thecocktaildb.com/images/ingredients/Sweet%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (406, N'Tabasco Sauce', N'https://thecocktaildb.com/images/ingredients/Tabasco%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (407, N'Tang', N'https://thecocktaildb.com/images/ingredients/Tang.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (408, N'Vanilla extract', N'https://thecocktaildb.com/images/ingredients/Vanilla%20extract.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (409, N'Vanilla Ice-Cream', N'https://thecocktaildb.com/images/ingredients/Vanilla%20Ice-Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (410, N'Vanilla liqueur', N'https://thecocktaildb.com/images/ingredients/Vanilla%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (411, N'Vanilla schnapps', N'https://thecocktaildb.com/images/ingredients/Vanilla%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (412, N'Vanilla syrup', N'https://thecocktaildb.com/images/ingredients/Vanilla%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (413, N'Vanilla vodka', N'https://thecocktaildb.com/images/ingredients/Vanilla%20vodka.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (414, N'Vanilla', N'https://thecocktaildb.com/images/ingredients/Vanilla.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (415, N'Vermouth', N'https://thecocktaildb.com/images/ingredients/Vermouth.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (416, N'Vinegar', N'https://thecocktaildb.com/images/ingredients/Vinegar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (417, N'Watermelon schnapps', N'https://thecocktaildb.com/images/ingredients/Watermelon%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (418, N'Whipped Cream', N'https://thecocktaildb.com/images/ingredients/Whipped%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (419, N'Whipping Cream', N'https://thecocktaildb.com/images/ingredients/Whipping%20Cream.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (420, N'White chocolate liqueur', N'https://thecocktaildb.com/images/ingredients/White%20chocolate%20liqueur.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (421, N'White Creme de Menthe', N'https://thecocktaildb.com/images/ingredients/White%20Creme%20de%20Menthe.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (422, N'White grape juice', N'https://thecocktaildb.com/images/ingredients/White%20grape%20juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (423, N'White port', N'https://thecocktaildb.com/images/ingredients/White%20port.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (424, N'White Rum', N'https://thecocktaildb.com/images/ingredients/White%20Rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (425, N'White Vinegar', N'https://thecocktaildb.com/images/ingredients/White%20Vinegar.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (426, N'White Wine', N'https://thecocktaildb.com/images/ingredients/White%20Wine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (427, N'Wild Turkey', N'https://thecocktaildb.com/images/ingredients/Wild%20Turkey.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (428, N'Wildberry schnapps', N'https://thecocktaildb.com/images/ingredients/Wildberry%20schnapps.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (429, N'Wine', N'https://thecocktaildb.com/images/ingredients/Wine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (430, N'Worcestershire Sauce', N'https://thecocktaildb.com/images/ingredients/Worcestershire%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (431, N'Yeast', N'https://thecocktaildb.com/images/ingredients/Yeast.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (432, N'Yellow Chartreuse', N'https://thecocktaildb.com/images/ingredients/Yellow%20Chartreuse.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (433, N'Yukon Jack', N'https://thecocktaildb.com/images/ingredients/Yukon%20Jack.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (434, N'Zima', N'https://thecocktaildb.com/images/ingredients/Zima.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (435, N'Caramel Sauce', N'https://thecocktaildb.com/images/ingredients/Caramel%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (436, N'Chocolate Sauce', N'https://thecocktaildb.com/images/ingredients/Chocolate%20Sauce.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (437, N'Lillet Blanc', N'https://thecocktaildb.com/images/ingredients/Lillet%20Blanc.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (438, N'Peach Bitters', N'https://thecocktaildb.com/images/ingredients/Peach%20Bitters.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (439, N'Mini-snickers bars', N'https://thecocktaildb.com/images/ingredients/Mini-snickers%20bars.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (440, N'Prosecco', N'https://thecocktaildb.com/images/ingredients/Prosecco.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (441, N'Salted Chocolate', N'https://thecocktaildb.com/images/ingredients/Salted%20Chocolate.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (442, N'Martini Rosso', N'https://thecocktaildb.com/images/ingredients/Martini%20Rosso.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (443, N'Martini Bianco', N'https://thecocktaildb.com/images/ingredients/Martini%20Bianco.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (444, N'Martini Extra Dry', N'https://thecocktaildb.com/images/ingredients/Martini%20Extra%20Dry.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (445, N'Fresh Lime Juice', N'https://thecocktaildb.com/images/ingredients/Fresh%20Lime%20Juice.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (446, N'Fresh Mint', N'https://thecocktaildb.com/images/ingredients/Fresh%20Mint.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (447, N'Rosemary', N'https://thecocktaildb.com/images/ingredients/Rosemary.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (448, N'Habanero Peppers', N'https://thecocktaildb.com/images/ingredients/Habanero%20Peppers.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (449, N'Ilegal Joven mezcal', N'https://thecocktaildb.com/images/ingredients/Ilegal%20Joven%20mezcal.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (450, N'Elderflower cordial', N'https://thecocktaildb.com/images/ingredients/Elderflower%20cordial.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (451, N'Rosso Vermouth', N'https://thecocktaildb.com/images/ingredients/Rosso%20Vermouth.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (452, N'Creme de Violette', N'https://thecocktaildb.com/images/ingredients/Creme%20de%20Violette.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (453, N'Cocchi Americano', N'https://thecocktaildb.com/images/ingredients/Cocchi%20Americano.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (454, N'White Vermouth', N'https://thecocktaildb.com/images/ingredients/White%20Vermouth.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (455, N'Dry Curacao', N'https://thecocktaildb.com/images/ingredients/Dry%20Curacao.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (456, N'Nocino', N'https://thecocktaildb.com/images/ingredients/Nocino.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (457, N'Averna', N'https://thecocktaildb.com/images/ingredients/Averna.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (458, N'Ramazzotti', N'https://thecocktaildb.com/images/ingredients/Ramazzotti.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (459, N'Fernet-Branca', N'https://thecocktaildb.com/images/ingredients/Fernet-Branca.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (460, N'Allspice Dram', N'https://thecocktaildb.com/images/ingredients/Allspice%20Dram.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (461, N'Falernum', N'https://thecocktaildb.com/images/ingredients/Falernum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (462, N'Singani', N'https://thecocktaildb.com/images/ingredients/Singani.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (463, N'Arrack', N'https://thecocktaildb.com/images/ingredients/Arrack.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (464, N'Blackstrap rum', N'https://thecocktaildb.com/images/ingredients/Blackstrap%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (465, N'Ginger Syrup', N'https://thecocktaildb.com/images/ingredients/Ginger%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (466, N'Honey syrup', N'https://thecocktaildb.com/images/ingredients/Honey%20syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (467, N'Blended Scotch', N'https://thecocktaildb.com/images/ingredients/Blended%20Scotch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (468, N'Islay single malt Scotch', N'https://thecocktaildb.com/images/ingredients/Islay%20single%20malt%20Scotch.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (469, N'151 proof rum', N'https://thecocktaildb.com/images/ingredients/151%20proof%20rum.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (470, N'Absinthe', N'https://thecocktaildb.com/images/ingredients/Absinthe.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (471, N'Creme de Mure', N'https://thecocktaildb.com/images/ingredients/Creme%20de%20Mure.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (472, N'Olive Brine', N'https://thecocktaildb.com/images/ingredients/Olive%20Brine.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (473, N'Pineapple Syrup', N'https://thecocktaildb.com/images/ingredients/Pineapple%20Syrup.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (474, N'St. Germain', N'https://thecocktaildb.com/images/ingredients/St.%20Germain.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (475, N'Lavender', N'https://thecocktaildb.com/images/ingredients/Lavender.png')
INSERT INTO [dbo].[Ingredients] ([idIngredient], [strIngredient], [strIngredientThumb]) VALUES (476, N'Whisky', N'https://thecocktaildb.com/images/ingredients/Whisky.png')
