INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (1, N'Vodka', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (2, N'Rum', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (3, N'Scotch', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (4, N'Whisky', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (5, N'Brandy', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (6, N'Gun', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (7, N'Tequila', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (8, N'Green Ginger Wine', 1, 1, NULL, CAST(1.0000 AS Money))
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (9, N'Gin', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (10, N'Dry Vermouth', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (11, N'Ginger ale', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (12, N'Jack Daniels', 1, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (13, N'Bacardi', 1, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (14, N'Beer', 1, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (15, N'Triple sec', 1, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (16, N'Red wine', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (17, N'Whiskey', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (18, N'Absolut Vodka', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (19, N'Midori Melon Liqueur', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (20, N'Sour Mix', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (21, N'Blue Curacao', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (22, N'Blueberry Schnapps', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (23, N'Ginger Ale', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Alcohol] ([Id], [Name], [Capacity], [Degrees], [Shelf life], [Price]) VALUES (24, N'Light Rum', NULL, NULL, NULL, NULL)
