INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (1, N'Water', 4, NULL, CAST(4.0000 AS Money))
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (2, N'Ice', 5, NULL, CAST(5.0000 AS Money))
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (3, N'Salt', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (4, N'Milk', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (5, N'Coffee', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (6, N'Mint', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (7, N'Sugar', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (8, N'Egg White', 10, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (9, N'Black Pepper', NULL, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (10, N'Chocolate', 1, NULL, NULL)
INSERT INTO [dbo].[Other] ([Id], [Name], [Amount], [Shelf life], [Price]) VALUES (11, N'Candy', NULL, NULL, NULL)
