CREATE TABLE Ingredients(
   idDrink               INTEGER NOT NULL PRIMARY KEY 
  ,strIngredient         VARCHAR(26) NOT NULL
  ,strIngredientThumb    VARCHAR(69) NOT NULL
);
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (1,'Light rum','https://www.thecocktaildb.com/images/ingredients/Light%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (2,'Applejack','https://www.thecocktaildb.com/images/ingredients/Applejack.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (3,'Gin','https://www.thecocktaildb.com/images/ingredients/Gin.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (4,'Dark rum','https://www.thecocktaildb.com/images/ingredients/Dark%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (5,'Sweet Vermouth','https://www.thecocktaildb.com/images/ingredients/Sweet%20Vermouth.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (6,'Strawberry schnapps','https://www.thecocktaildb.com/images/ingredients/Strawberry%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (7,'Scotch','https://www.thecocktaildb.com/images/ingredients/Scotch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (8,'Apricot brandy','https://www.thecocktaildb.com/images/ingredients/Apricot%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (9,'Triple sec','https://www.thecocktaildb.com/images/ingredients/Triple%20sec.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (10,'Southern Comfort','https://www.thecocktaildb.com/images/ingredients/Southern%20Comfort.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (11,'Orange bitters','https://www.thecocktaildb.com/images/ingredients/Orange%20bitters.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (12,'Brandy','https://www.thecocktaildb.com/images/ingredients/Brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (13,'Lemon vodka','https://www.thecocktaildb.com/images/ingredients/Lemon%20vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (14,'Blended whiskey','https://www.thecocktaildb.com/images/ingredients/Blended%20whiskey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (15,'Dry Vermouth','https://www.thecocktaildb.com/images/ingredients/Dry%20Vermouth.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (16,'Amaretto','https://www.thecocktaildb.com/images/ingredients/Amaretto.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (17,'Tea','https://www.thecocktaildb.com/images/ingredients/Tea.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (18,'Champagne','https://www.thecocktaildb.com/images/ingredients/Champagne.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (19,'Coffee liqueur','https://www.thecocktaildb.com/images/ingredients/Coffee%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (20,'Bourbon','https://thecocktaildb.com/images/ingredients/Bourbon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (21,'Tequila','https://thecocktaildb.com/images/ingredients/Tequila.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (22,'Vodka','https://thecocktaildb.com/images/ingredients/Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (23,'Anejo rum','https://thecocktaildb.com/images/ingredients/Aejo%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (24,'Bitters','https://thecocktaildb.com/images/ingredients/Bitters.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (25,'Sugar','https://thecocktaildb.com/images/ingredients/Sugar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (26,'Kahlua','https://thecocktaildb.com/images/ingredients/Kahlua.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (27,'demerara Sugar','https://thecocktaildb.com/images/ingredients/demerara%20Sugar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (28,'Dubonnet Rouge','https://thecocktaildb.com/images/ingredients/Dubonnet%20Rouge.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (29,'Lime juice','https://thecocktaildb.com/images/ingredients/Lime%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (30,'Irish whiskey','https://thecocktaildb.com/images/ingredients/Irish%20whiskey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (31,'Apple brandy','https://thecocktaildb.com/images/ingredients/Apple%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (32,'Carbonated water','https://thecocktaildb.com/images/ingredients/Carbonated%20water.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (33,'Cherry brandy','https://thecocktaildb.com/images/ingredients/Cherry%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (34,'Creme de Cacao','https://thecocktaildb.com/images/ingredients/Creme%20de%20Cacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (35,'Grenadine','https://thecocktaildb.com/images/ingredients/Grenadine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (36,'Port','https://thecocktaildb.com/images/ingredients/Port.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (37,'Coffee brandy','https://thecocktaildb.com/images/ingredients/Coffee%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (38,'Red wine','https://thecocktaildb.com/images/ingredients/Red%20wine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (39,'Rum','https://thecocktaildb.com/images/ingredients/Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (40,'Grapefruit juice','https://thecocktaildb.com/images/ingredients/Grapefruit%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (41,'Ricard','https://thecocktaildb.com/images/ingredients/Ricard.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (42,'Sherry','https://thecocktaildb.com/images/ingredients/Sherry.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (43,'Cognac','https://thecocktaildb.com/images/ingredients/Cognac.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (44,'Sloe gin','https://thecocktaildb.com/images/ingredients/Sloe%20gin.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (45,'Apple juice','https://thecocktaildb.com/images/ingredients/Apple%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (46,'Pineapple juice','https://thecocktaildb.com/images/ingredients/Pineapple%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (47,'Lemon juice','https://thecocktaildb.com/images/ingredients/Lemon%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (48,'Sugar syrup','https://thecocktaildb.com/images/ingredients/Sugar%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (49,'Milk','https://thecocktaildb.com/images/ingredients/Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (50,'Strawberries','https://thecocktaildb.com/images/ingredients/Strawberries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (51,'Chocolate syrup','https://thecocktaildb.com/images/ingredients/Chocolate%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (52,'Yoghurt','https://thecocktaildb.com/images/ingredients/Yoghurt.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (53,'Mango','https://thecocktaildb.com/images/ingredients/Mango.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (54,'Ginger','https://thecocktaildb.com/images/ingredients/Ginger.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (55,'Lime','https://thecocktaildb.com/images/ingredients/Lime.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (56,'Cantaloupe','https://thecocktaildb.com/images/ingredients/Cantaloupe.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (57,'Berries','https://thecocktaildb.com/images/ingredients/Berries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (58,'Grapes','https://thecocktaildb.com/images/ingredients/Grapes.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (59,'Kiwi','https://thecocktaildb.com/images/ingredients/Kiwi.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (60,'Tomato juice','https://thecocktaildb.com/images/ingredients/Tomato%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (61,'Cocoa powder','https://thecocktaildb.com/images/ingredients/Cocoa%20powder.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (62,'Chocolate','https://thecocktaildb.com/images/ingredients/Chocolate.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (63,'Heavy cream','https://thecocktaildb.com/images/ingredients/Heavy%20cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (64,'Galliano','https://thecocktaildb.com/images/ingredients/Galliano.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (65,'Peach Vodka','https://thecocktaildb.com/images/ingredients/Peach%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (66,'Ouzo','https://thecocktaildb.com/images/ingredients/Ouzo.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (67,'Coffee','https://thecocktaildb.com/images/ingredients/Coffee.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (68,'Spiced rum','https://thecocktaildb.com/images/ingredients/Spiced%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (69,'Water','https://thecocktaildb.com/images/ingredients/Water.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (70,'Espresso','https://thecocktaildb.com/images/ingredients/Espresso.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (71,'Angelica root','https://thecocktaildb.com/images/ingredients/Angelica%20root.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (72,'Orange','https://thecocktaildb.com/images/ingredients/Orange.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (73,'Cranberries','https://thecocktaildb.com/images/ingredients/Cranberries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (74,'Johnnie Walker','https://thecocktaildb.com/images/ingredients/Johnnie%20Walker.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (75,'Apple cider','https://thecocktaildb.com/images/ingredients/Apple%20cider.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (76,'Everclear','https://thecocktaildb.com/images/ingredients/Everclear.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (77,'Cranberry juice','https://thecocktaildb.com/images/ingredients/Cranberry%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (78,'Egg yolk','https://thecocktaildb.com/images/ingredients/Egg%20yolk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (79,'Egg','https://thecocktaildb.com/images/ingredients/Egg.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (80,'Grape juice','https://thecocktaildb.com/images/ingredients/Grape%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (81,'Peach nectar','https://thecocktaildb.com/images/ingredients/Peach%20nectar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (82,'Lemon','https://thecocktaildb.com/images/ingredients/Lemon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (83,'Firewater','https://thecocktaildb.com/images/ingredients/Firewater.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (84,'Lemonade','https://thecocktaildb.com/images/ingredients/Lemonade.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (85,'Lager','https://thecocktaildb.com/images/ingredients/Lager.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (86,'Whiskey','https://thecocktaildb.com/images/ingredients/Whiskey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (87,'Absolut Citron','https://thecocktaildb.com/images/ingredients/Absolut%20Citron.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (88,'Pisco','https://thecocktaildb.com/images/ingredients/Pisco.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (89,'Irish cream','https://thecocktaildb.com/images/ingredients/Irish%20cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (90,'Ale','https://thecocktaildb.com/images/ingredients/Ale.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (91,'Chocolate liqueur','https://thecocktaildb.com/images/ingredients/Chocolate%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (92,'Midori melon liqueur','https://thecocktaildb.com/images/ingredients/Midori%20melon%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (93,'Sambuca','https://thecocktaildb.com/images/ingredients/Sambuca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (94,'Cider','https://thecocktaildb.com/images/ingredients/Cider.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (95,'Sprite','https://thecocktaildb.com/images/ingredients/Sprite.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (96,'7-Up','https://thecocktaildb.com/images/ingredients/7-Up.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (97,'Blackberry brandy','https://thecocktaildb.com/images/ingredients/Blackberry%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (98,'Peppermint schnapps','https://thecocktaildb.com/images/ingredients/Peppermint%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (99,'Creme de Cassis','https://thecocktaildb.com/images/ingredients/Creme%20de%20Cassis.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (100,'Jack Daniels','https://thecocktaildb.com/images/ingredients/Jack%20Daniels.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (101,'Mint','https://thecocktaildb.com/images/ingredients/Mint.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (102,'Maraschino Cherry','https://thecocktaildb.com/images/ingredients/Maraschino%20Cherry.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (103,'Lemon Peel','https://thecocktaildb.com/images/ingredients/Lemon%20Peel.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (104,'Wormwood','https://thecocktaildb.com/images/ingredients/Wormwood.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (105,'Ice','https://thecocktaildb.com/images/ingredients/Ice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (106,'Jelly','https://thecocktaildb.com/images/ingredients/Jelly.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (107,'Absolut Kurant','https://thecocktaildb.com/images/ingredients/Absolut%20Kurant.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (108,'Absolut Peppar','https://thecocktaildb.com/images/ingredients/Absolut%20Peppar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (109,'Absolut Vodka','https://thecocktaildb.com/images/ingredients/Absolut%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (110,'Advocaat','https://thecocktaildb.com/images/ingredients/Advocaat.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (111,'Aftershock','https://thecocktaildb.com/images/ingredients/Aftershock.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (112,'Agave Syrup','https://thecocktaildb.com/images/ingredients/Agave%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (113,'Allspice','https://thecocktaildb.com/images/ingredients/Allspice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (114,'Almond Extract','https://thecocktaildb.com/images/ingredients/Almond%20Extract.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (115,'Almond Flavoring','https://thecocktaildb.com/images/ingredients/Almond%20Flavoring.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (116,'Almond','https://thecocktaildb.com/images/ingredients/Almond.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (117,'Angostura Bitters','https://thecocktaildb.com/images/ingredients/Angostura%20Bitters.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (118,'Anis','https://thecocktaildb.com/images/ingredients/Anis.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (119,'Anise','https://thecocktaildb.com/images/ingredients/Anise.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (120,'Anisette','https://thecocktaildb.com/images/ingredients/Anisette.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (121,'Aperol','https://thecocktaildb.com/images/ingredients/Aperol.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (122,'Apfelkorn','https://thecocktaildb.com/images/ingredients/Apfelkorn.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (123,'Apple Schnapps','https://thecocktaildb.com/images/ingredients/Apple%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (124,'Apple','https://thecocktaildb.com/images/ingredients/Apple.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (125,'Apricot Nectar','https://thecocktaildb.com/images/ingredients/Apricot%20Nectar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (126,'Apricot','https://thecocktaildb.com/images/ingredients/Apricot.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (127,'Aquavit','https://thecocktaildb.com/images/ingredients/Aquavit.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (128,'Asafoetida','https://thecocktaildb.com/images/ingredients/Asafoetida.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (129,'Bacardi Limon','https://thecocktaildb.com/images/ingredients/Bacardi%20Limon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (130,'Bacardi','https://thecocktaildb.com/images/ingredients/Bacardi.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (131,'Baileys Irish Cream','https://thecocktaildb.com/images/ingredients/Baileys%20Irish%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (132,'Banana Liqueur','https://thecocktaildb.com/images/ingredients/Banana%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (133,'Banana Rum','https://thecocktaildb.com/images/ingredients/Banana%20Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (134,'Banana Syrup','https://thecocktaildb.com/images/ingredients/Banana%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (135,'Banana','https://thecocktaildb.com/images/ingredients/Banana.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (136,'Barenjager','https://thecocktaildb.com/images/ingredients/Barenjager.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (137,'Basil','https://thecocktaildb.com/images/ingredients/Basil.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (138,'Beef Stock','https://thecocktaildb.com/images/ingredients/Beef%20Stock.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (139,'Beer','https://thecocktaildb.com/images/ingredients/Beer.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (140,'Benedictine','https://thecocktaildb.com/images/ingredients/Benedictine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (141,'Bitter lemon','https://thecocktaildb.com/images/ingredients/Bitter%20lemon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (142,'Black Pepper','https://thecocktaildb.com/images/ingredients/Black%20Pepper.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (143,'Black Rum','https://thecocktaildb.com/images/ingredients/Black%20Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (144,'Black Sambuca','https://thecocktaildb.com/images/ingredients/Black%20Sambuca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (145,'Blackberries','https://thecocktaildb.com/images/ingredients/Blackberries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (146,'Blackberry Schnapps','https://thecocktaildb.com/images/ingredients/Blackberry%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (147,'Blackcurrant Cordial','https://thecocktaildb.com/images/ingredients/Blackcurrant%20Cordial.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (148,'Blackcurrant Schnapps','https://thecocktaildb.com/images/ingredients/Blackcurrant%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (149,'Blackcurrant Squash','https://thecocktaildb.com/images/ingredients/Blackcurrant%20Squash.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (150,'Blue Curacao','https://thecocktaildb.com/images/ingredients/Blue%20Curacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (151,'Blue Maui','https://thecocktaildb.com/images/ingredients/Blue%20Maui.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (152,'Blueberries','https://thecocktaildb.com/images/ingredients/Blueberries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (153,'Blueberry Schnapps','https://thecocktaildb.com/images/ingredients/Blueberry%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (154,'Brown Sugar','https://thecocktaildb.com/images/ingredients/Brown%20Sugar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (155,'Butter','https://thecocktaildb.com/images/ingredients/Butter.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (156,'Butterscotch Schnapps','https://thecocktaildb.com/images/ingredients/Butterscotch%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (157,'Cachaca','https://thecocktaildb.com/images/ingredients/Cachaca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (158,'Calvados','https://thecocktaildb.com/images/ingredients/Calvados.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (159,'Campari','https://thecocktaildb.com/images/ingredients/Campari.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (160,'Canadian Whisky','https://thecocktaildb.com/images/ingredients/Canadian%20Whisky.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (161,'Candy','https://thecocktaildb.com/images/ingredients/Candy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (162,'Caramel Coloring','https://thecocktaildb.com/images/ingredients/Caramel%20Coloring.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (163,'Carbonated Soft Drink','https://thecocktaildb.com/images/ingredients/Carbonated%20Soft%20Drink.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (164,'Cardamom','https://thecocktaildb.com/images/ingredients/Cardamom.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (165,'Cayenne Pepper','https://thecocktaildb.com/images/ingredients/Cayenne%20Pepper.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (166,'Celery Salt','https://thecocktaildb.com/images/ingredients/Celery%20Salt.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (167,'Celery','https://thecocktaildb.com/images/ingredients/Celery.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (168,'Chambord Raspberry Liqueur','https://thecocktaildb.com/images/ingredients/Chambord%20Raspberry%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (169,'Cherries','https://thecocktaildb.com/images/ingredients/Cherries.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (170,'Cherry Cola','https://thecocktaildb.com/images/ingredients/Cherry%20Cola.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (171,'Cherry Grenadine','https://thecocktaildb.com/images/ingredients/Cherry%20Grenadine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (172,'Cherry Heering','https://thecocktaildb.com/images/ingredients/Cherry%20Heering.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (173,'Cherry Juice','https://thecocktaildb.com/images/ingredients/Cherry%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (174,'Cherry Liqueur','https://thecocktaildb.com/images/ingredients/Cherry%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (175,'Cherry','https://thecocktaildb.com/images/ingredients/Cherry.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (176,'Chocolate Ice-cream','https://thecocktaildb.com/images/ingredients/Chocolate%20Ice-cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (177,'Chocolate Milk','https://thecocktaildb.com/images/ingredients/Chocolate%20Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (178,'Cinnamon Schnapps','https://thecocktaildb.com/images/ingredients/Cinnamon%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (179,'Cinnamon','https://thecocktaildb.com/images/ingredients/Cinnamon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (180,'Citrus Vodka','https://thecocktaildb.com/images/ingredients/Citrus%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (181,'Clamato Juice','https://thecocktaildb.com/images/ingredients/Clamato%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (182,'Cloves','https://thecocktaildb.com/images/ingredients/Cloves.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (183,'Club Soda','https://thecocktaildb.com/images/ingredients/Club%20Soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (184,'Coca-Cola','https://thecocktaildb.com/images/ingredients/Coca-Cola.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (185,'Cocktail Onion','https://thecocktaildb.com/images/ingredients/Cocktail%20Onion.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (186,'Coconut Cream','https://thecocktaildb.com/images/ingredients/Coconut%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (187,'Coconut Liqueur','https://thecocktaildb.com/images/ingredients/Coconut%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (188,'Coconut Milk','https://thecocktaildb.com/images/ingredients/Coconut%20Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (189,'Coconut Rum','https://thecocktaildb.com/images/ingredients/Coconut%20Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (190,'Coconut Syrup','https://thecocktaildb.com/images/ingredients/Coconut%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (191,'Cointreau','https://thecocktaildb.com/images/ingredients/Cointreau.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (192,'Cola','https://thecocktaildb.com/images/ingredients/Cola.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (193,'Cold Water','https://thecocktaildb.com/images/ingredients/Cold%20Water.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (194,'Condensed Milk','https://thecocktaildb.com/images/ingredients/Condensed%20Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (195,'Coriander','https://thecocktaildb.com/images/ingredients/Coriander.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (196,'Corn Syrup','https://thecocktaildb.com/images/ingredients/Corn%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (197,'Cornstarch','https://thecocktaildb.com/images/ingredients/Cornstarch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (198,'Corona','https://thecocktaildb.com/images/ingredients/Corona.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (199,'Cranberry Liqueur','https://thecocktaildb.com/images/ingredients/Cranberry%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (201,'Cranberry Vodka','https://thecocktaildb.com/images/ingredients/Cranberry%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (202,'Cream of Coconut','https://thecocktaildb.com/images/ingredients/Cream%20of%20Coconut.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (203,'Cream Sherry','https://thecocktaildb.com/images/ingredients/Cream%20Sherry.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (204,'Cream Soda','https://thecocktaildb.com/images/ingredients/Cream%20Soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (205,'Cream','https://thecocktaildb.com/images/ingredients/Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (206,'Creme De Almond','https://thecocktaildb.com/images/ingredients/Creme%20De%20Almond.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (207,'Creme De Banane','https://thecocktaildb.com/images/ingredients/Creme%20De%20Banane.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (208,'Creme De Noyaux','https://thecocktaildb.com/images/ingredients/Creme%20De%20Noyaux.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (209,'Creme Fraiche','https://thecocktaildb.com/images/ingredients/Creme%20Fraiche.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (210,'Crown Royal','https://thecocktaildb.com/images/ingredients/Crown%20Royal.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (211,'Crystal Light','https://thecocktaildb.com/images/ingredients/Crystal%20Light.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (212,'Cucumber','https://thecocktaildb.com/images/ingredients/Cucumber.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (213,'Cumin Powder','https://thecocktaildb.com/images/ingredients/Cumin%20Powder.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (214,'Cumin Seed','https://thecocktaildb.com/images/ingredients/Cumin%20Seed.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (215,'Curacao','https://thecocktaildb.com/images/ingredients/Curacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (216,'Cynar','https://thecocktaildb.com/images/ingredients/Cynar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (217,'Daiquiri Mix','https://thecocktaildb.com/images/ingredients/Daiquiri%20Mix.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (218,'Dark Chocolate','https://thecocktaildb.com/images/ingredients/Dark%20Chocolate.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (219,'Dark Creme De Cacao','https://thecocktaildb.com/images/ingredients/Dark%20Creme%20De%20Cacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (220,'Dark Soy Sauce','https://thecocktaildb.com/images/ingredients/Dark%20Soy%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (221,'Dr. Pepper','https://thecocktaildb.com/images/ingredients/Dr.%20Pepper.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (222,'Drambuie','https://thecocktaildb.com/images/ingredients/Drambuie.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (223,'Dried Oregano','https://thecocktaildb.com/images/ingredients/Dried%20Oregano.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (224,'Dubonnet Blanc','https://thecocktaildb.com/images/ingredients/Dubonnet%20Blanc.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (225,'Egg White','https://thecocktaildb.com/images/ingredients/Egg%20White.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (226,'Eggnog','https://thecocktaildb.com/images/ingredients/Eggnog.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (227,'Erin Cream','https://thecocktaildb.com/images/ingredients/Erin%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (228,'Fanta','https://thecocktaildb.com/images/ingredients/Fanta.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (229,'Fennel Seeds','https://thecocktaildb.com/images/ingredients/Fennel%20Seeds.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (230,'Flaked Almonds','https://thecocktaildb.com/images/ingredients/Flaked%20Almonds.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (231,'Food Coloring','https://thecocktaildb.com/images/ingredients/Food%20Coloring.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (232,'Forbidden Fruit','https://thecocktaildb.com/images/ingredients/Forbidden%20Fruit.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (233,'Frangelico','https://thecocktaildb.com/images/ingredients/Frangelico.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (234,'Fresca','https://thecocktaildb.com/images/ingredients/Fresca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (235,'Fresh Basil','https://thecocktaildb.com/images/ingredients/Fresh%20Basil.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (236,'Fresh Lemon Juice','https://thecocktaildb.com/images/ingredients/Fresh%20Lemon%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (237,'Fruit Juice','https://thecocktaildb.com/images/ingredients/Fruit%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (238,'Fruit Punch','https://thecocktaildb.com/images/ingredients/Fruit%20Punch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (239,'Fruit','https://thecocktaildb.com/images/ingredients/Fruit.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (240,'Garlic Sauce','https://thecocktaildb.com/images/ingredients/Garlic%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (241,'Gatorade','https://thecocktaildb.com/images/ingredients/Gatorade.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (242,'Ginger Ale','https://thecocktaildb.com/images/ingredients/Ginger%20Ale.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (243,'Ginger Beer','https://thecocktaildb.com/images/ingredients/Ginger%20Beer.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (244,'Glycerine','https://thecocktaildb.com/images/ingredients/Glycerine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (245,'Godiva Liqueur','https://thecocktaildb.com/images/ingredients/Godiva%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (246,'Gold rum','https://thecocktaildb.com/images/ingredients/Gold%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (247,'Gold Tequila','https://thecocktaildb.com/images/ingredients/Gold%20Tequila.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (248,'Goldschlager','https://thecocktaildb.com/images/ingredients/Goldschlager.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (249,'Grain Alcohol','https://thecocktaildb.com/images/ingredients/Grain%20Alcohol.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (250,'Grand Marnier','https://thecocktaildb.com/images/ingredients/Grand%20Marnier.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (251,'Granulated Sugar','https://thecocktaildb.com/images/ingredients/Granulated%20Sugar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (252,'Grape soda','https://thecocktaildb.com/images/ingredients/Grape%20soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (253,'Green Chartreuse','https://thecocktaildb.com/images/ingredients/Green%20Chartreuse.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (254,'Green Creme de Menthe','https://thecocktaildb.com/images/ingredients/Green%20Creme%20de%20Menthe.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (255,'Green Ginger Wine','https://thecocktaildb.com/images/ingredients/Green%20Ginger%20Wine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (256,'Green Olives','https://thecocktaildb.com/images/ingredients/Green%20Olives.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (257,'Ground Ginger','https://thecocktaildb.com/images/ingredients/Ground%20Ginger.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (258,'Guava juice','https://thecocktaildb.com/images/ingredients/Guava%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (259,'Guinness stout','https://thecocktaildb.com/images/ingredients/Guinness%20stout.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (260,'Guinness','https://thecocktaildb.com/images/ingredients/Guinness.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (261,'Half-and-half','https://thecocktaildb.com/images/ingredients/Half-and-half.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (262,'Hawaiian punch','https://thecocktaildb.com/images/ingredients/Hawaiian%20punch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (263,'Hazelnut liqueur','https://thecocktaildb.com/images/ingredients/Hazelnut%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (264,'Honey','https://thecocktaildb.com/images/ingredients/Honey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (265,'Hooch','https://thecocktaildb.com/images/ingredients/Hooch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (266,'Hot Chocolate','https://thecocktaildb.com/images/ingredients/Hot%20Chocolate.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (267,'Hot Damn','https://thecocktaildb.com/images/ingredients/Hot%20Damn.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (268,'Hot Sauce','https://thecocktaildb.com/images/ingredients/Hot%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (269,'Hpnotiq','https://thecocktaildb.com/images/ingredients/Hpnotiq.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (270,'Ice-Cream','https://thecocktaildb.com/images/ingredients/Ice-Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (271,'Iced tea','https://thecocktaildb.com/images/ingredients/Iced%20tea.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (272,'Jello','https://thecocktaildb.com/images/ingredients/Jello.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (273,'Jagermeister','https://thecocktaildb.com/images/ingredients/Jagermeister.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (274,'Jim Beam','https://thecocktaildb.com/images/ingredients/Jim%20Beam.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (275,'Key Largo Schnapps','https://thecocktaildb.com/images/ingredients/Key%20Largo%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (276,'Kirschwasser','https://thecocktaildb.com/images/ingredients/Kirschwasser.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (277,'Kiwi liqueur','https://thecocktaildb.com/images/ingredients/Kiwi%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (278,'Kool-Aid','https://thecocktaildb.com/images/ingredients/Kool-Aid.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (279,'Kummel','https://thecocktaildb.com/images/ingredients/Kummel.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (280,'Lemon soda','https://thecocktaildb.com/images/ingredients/Lemon%20soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (281,'Lemon-lime soda','https://thecocktaildb.com/images/ingredients/Lemon-lime%20soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (282,'lemon-lime','https://thecocktaildb.com/images/ingredients/lemon-lime.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (283,'lemon','https://thecocktaildb.com/images/ingredients/lemon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (284,'Licorice Root','https://thecocktaildb.com/images/ingredients/Licorice%20Root.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (285,'Light Cream','https://thecocktaildb.com/images/ingredients/Light%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (286,'Lillet','https://thecocktaildb.com/images/ingredients/Lillet.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (287,'Lime juice cordial','https://thecocktaildb.com/images/ingredients/Lime%20juice%20cordial.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (288,'Lime liqueur','https://thecocktaildb.com/images/ingredients/Lime%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (289,'Lime Peel','https://thecocktaildb.com/images/ingredients/Lime%20Peel.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (290,'Lime vodka','https://thecocktaildb.com/images/ingredients/Lime%20vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (291,'Limeade','https://thecocktaildb.com/images/ingredients/Limeade.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (292,'Madeira','https://thecocktaildb.com/images/ingredients/Madeira.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (293,'Malibu Rum','https://thecocktaildb.com/images/ingredients/Malibu%20Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (294,'Mandarin','https://thecocktaildb.com/images/ingredients/Mandarin.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (295,'Mandarine napoleon','https://thecocktaildb.com/images/ingredients/Mandarine%20napoleon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (296,'Maple syrup','https://thecocktaildb.com/images/ingredients/Maple%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (297,'Maraschino cherry juice','https://thecocktaildb.com/images/ingredients/Maraschino%20cherry%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (298,'Maraschino Liqueur','https://thecocktaildb.com/images/ingredients/Maraschino%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (299,'Margarita mix','https://thecocktaildb.com/images/ingredients/Margarita%20mix.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (300,'Marjoram leaves','https://thecocktaildb.com/images/ingredients/Marjoram%20leaves.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (301,'Marshmallows','https://thecocktaildb.com/images/ingredients/Marshmallows.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (302,'Maui','https://thecocktaildb.com/images/ingredients/Maui.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (303,'Melon Liqueur','https://thecocktaildb.com/images/ingredients/Melon%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (304,'Melon Vodka','https://thecocktaildb.com/images/ingredients/Melon%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (305,'Mezcal','https://thecocktaildb.com/images/ingredients/Mezcal.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (306,'Midori','https://thecocktaildb.com/images/ingredients/Midori.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (307,'Mint syrup','https://thecocktaildb.com/images/ingredients/Mint%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (308,'Mountain Dew','https://thecocktaildb.com/images/ingredients/Mountain%20Dew.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (309,'Nutmeg','https://thecocktaildb.com/images/ingredients/Nutmeg.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (310,'Olive Oil','https://thecocktaildb.com/images/ingredients/Olive%20Oil.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (311,'Olive','https://thecocktaildb.com/images/ingredients/Olive.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (312,'Onion','https://thecocktaildb.com/images/ingredients/Onion.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (313,'Orange Curacao','https://thecocktaildb.com/images/ingredients/Orange%20Curacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (314,'Orange Juice','https://thecocktaildb.com/images/ingredients/Orange%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (315,'Orange liqueur','https://thecocktaildb.com/images/ingredients/Orange%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (316,'Orange Peel','https://thecocktaildb.com/images/ingredients/Orange%20Peel.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (317,'Orange rum','https://thecocktaildb.com/images/ingredients/Orange%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (318,'Orange Soda','https://thecocktaildb.com/images/ingredients/Orange%20Soda.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (319,'Orange spiral','https://thecocktaildb.com/images/ingredients/Orange%20spiral.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (320,'Orange vodka','https://thecocktaildb.com/images/ingredients/Orange%20vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (321,'Oreo cookie','https://thecocktaildb.com/images/ingredients/Oreo%20cookie.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (322,'Orgeat Syrup','https://thecocktaildb.com/images/ingredients/Orgeat%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (323,'Oyster Sauce','https://thecocktaildb.com/images/ingredients/Oyster%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (324,'Papaya juice','https://thecocktaildb.com/images/ingredients/Papaya%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (325,'Papaya','https://thecocktaildb.com/images/ingredients/Papaya.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (326,'Parfait amour','https://thecocktaildb.com/images/ingredients/Parfait%20amour.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (327,'Passion fruit juice','https://thecocktaildb.com/images/ingredients/Passion%20fruit%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (328,'Passion fruit syrup','https://thecocktaildb.com/images/ingredients/Passion%20fruit%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (329,'Passoa','https://thecocktaildb.com/images/ingredients/Passoa.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (330,'Peach brandy','https://thecocktaildb.com/images/ingredients/Peach%20brandy.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (331,'Peach juice','https://thecocktaildb.com/images/ingredients/Peach%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (332,'Peach liqueur','https://thecocktaildb.com/images/ingredients/Peach%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (333,'Peach Schnapps','https://thecocktaildb.com/images/ingredients/Peach%20Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (334,'Peach','https://thecocktaildb.com/images/ingredients/Peach.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (335,'Peachtree schnapps','https://thecocktaildb.com/images/ingredients/Peachtree%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (336,'Peanut Oil','https://thecocktaildb.com/images/ingredients/Peanut%20Oil.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (337,'Pepper','https://thecocktaildb.com/images/ingredients/Pepper.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (338,'Peppermint extract','https://thecocktaildb.com/images/ingredients/Peppermint%20extract.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (339,'Pepsi Cola','https://thecocktaildb.com/images/ingredients/Pepsi%20Cola.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (340,'Pernod','https://thecocktaildb.com/images/ingredients/Pernod.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (341,'Peychaud bitters','https://thecocktaildb.com/images/ingredients/Peychaud%20bitters.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (342,'Pina colada mix','https://thecocktaildb.com/images/ingredients/Pina%20colada%20mix.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (343,'Pineapple rum','https://thecocktaildb.com/images/ingredients/Pineapple%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (344,'Pineapple vodka','https://thecocktaildb.com/images/ingredients/Pineapple%20vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (345,'Pineapple-orange-banana juice','https://thecocktaildb.com/images/ingredients/Pineapple-orange-banana%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (346,'Pineapple','https://thecocktaildb.com/images/ingredients/Pineapple.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (347,'Pink lemonade','https://thecocktaildb.com/images/ingredients/Pink%20lemonade.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (348,'Pisang Ambon','https://thecocktaildb.com/images/ingredients/Pisang%20Ambon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (349,'Plain Chocolate','https://thecocktaildb.com/images/ingredients/Plain%20Chocolate.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (350,'Plain Flour','https://thecocktaildb.com/images/ingredients/Plain%20Flour.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (351,'Plums','https://thecocktaildb.com/images/ingredients/Plums.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (352,'Powdered Sugar','https://thecocktaildb.com/images/ingredients/Powdered%20Sugar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (353,'Purple passion','https://thecocktaildb.com/images/ingredients/Purple%20passion.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (354,'Raisins','https://thecocktaildb.com/images/ingredients/Raisins.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (355,'Raspberry cordial','https://thecocktaildb.com/images/ingredients/Raspberry%20cordial.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (356,'Raspberry Jam','https://thecocktaildb.com/images/ingredients/Raspberry%20Jam.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (357,'Raspberry Juice','https://thecocktaildb.com/images/ingredients/Raspberry%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (358,'Raspberry Liqueur','https://thecocktaildb.com/images/ingredients/Raspberry%20Liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (359,'Raspberry schnapps','https://thecocktaildb.com/images/ingredients/Raspberry%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (360,'Raspberry syrup','https://thecocktaildb.com/images/ingredients/Raspberry%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (361,'Raspberry Vodka','https://thecocktaildb.com/images/ingredients/Raspberry%20Vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (362,'Red Chile Flakes','https://thecocktaildb.com/images/ingredients/Red%20Chile%20Flakes.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (363,'Red Chili Flakes','https://thecocktaildb.com/images/ingredients/Red%20Chili%20Flakes.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (364,'Red Hot Chili Flakes','https://thecocktaildb.com/images/ingredients/Red%20Hot%20Chili%20Flakes.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (365,'Rhubarb','https://thecocktaildb.com/images/ingredients/Rhubarb.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (366,'Rock Salt','https://thecocktaildb.com/images/ingredients/Rock%20Salt.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (367,'Root beer schnapps','https://thecocktaildb.com/images/ingredients/Root%20beer%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (368,'Root beer','https://thecocktaildb.com/images/ingredients/Root%20beer.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (369,'Roses sweetened lime juice','https://thecocktaildb.com/images/ingredients/Roses%20sweetened%20lime%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (370,'Rosewater','https://thecocktaildb.com/images/ingredients/Rosewater.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (371,'Rumple Minze','https://thecocktaildb.com/images/ingredients/Rumple%20Minze.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (372,'Rye Whiskey','https://thecocktaildb.com/images/ingredients/Rye%20Whiskey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (373,'Sake','https://thecocktaildb.com/images/ingredients/Sake.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (374,'Salt','https://thecocktaildb.com/images/ingredients/Salt.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (375,'Sarsaparilla','https://thecocktaildb.com/images/ingredients/Sarsaparilla.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (376,'Schnapps','https://thecocktaildb.com/images/ingredients/Schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (377,'Schweppes Lemon','https://thecocktaildb.com/images/ingredients/Schweppes%20Lemon.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (378,'Schweppes Russchian','https://thecocktaildb.com/images/ingredients/Schweppes%20Russchian.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (379,'Sherbet','https://thecocktaildb.com/images/ingredients/Sherbet.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (380,'Sirup of roses','https://thecocktaildb.com/images/ingredients/Sirup%20of%20roses.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (381,'Soda Water','https://thecocktaildb.com/images/ingredients/Soda%20Water.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (382,'Sour Apple Pucker','https://thecocktaildb.com/images/ingredients/Sour%20Apple%20Pucker.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (383,'Sour Mix','https://thecocktaildb.com/images/ingredients/Sour%20Mix.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (384,'Soy Milk','https://thecocktaildb.com/images/ingredients/Soy%20Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (385,'Soy Sauce','https://thecocktaildb.com/images/ingredients/Soy%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (386,'Soya Milk','https://thecocktaildb.com/images/ingredients/Soya%20Milk.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (387,'Soya Sauce','https://thecocktaildb.com/images/ingredients/Soya%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (388,'Squeezed Orange','https://thecocktaildb.com/images/ingredients/Squeezed%20Orange.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (389,'Squirt','https://thecocktaildb.com/images/ingredients/Squirt.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (390,'Tawny port','https://thecocktaildb.com/images/ingredients/Tawny%20port.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (391,'Tennessee whiskey','https://thecocktaildb.com/images/ingredients/Tennessee%20whiskey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (392,'Tequila rose','https://thecocktaildb.com/images/ingredients/Tequila%20rose.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (393,'Tia Maria','https://thecocktaildb.com/images/ingredients/Tia%20Maria.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (394,'Tomato','https://thecocktaildb.com/images/ingredients/Tomato.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (395,'Tonic Water','https://thecocktaildb.com/images/ingredients/Tonic%20Water.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (396,'Tropicana','https://thecocktaildb.com/images/ingredients/Tropicana.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (397,'Tuaca','https://thecocktaildb.com/images/ingredients/Tuaca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (398,'Strawberry juice','https://thecocktaildb.com/images/ingredients/Strawberry%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (399,'Strawberry liqueur','https://thecocktaildb.com/images/ingredients/Strawberry%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (400,'Strawberry syrup','https://thecocktaildb.com/images/ingredients/Strawberry%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (401,'Sunny delight','https://thecocktaildb.com/images/ingredients/Sunny%20delight.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (402,'Surge','https://thecocktaildb.com/images/ingredients/Surge.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (403,'Swedish punsch','https://thecocktaildb.com/images/ingredients/Swedish%20punsch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (404,'Sweet and Sour','https://thecocktaildb.com/images/ingredients/Sweet%20and%20Sour.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (405,'Sweet Cream','https://thecocktaildb.com/images/ingredients/Sweet%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (406,'Tabasco Sauce','https://thecocktaildb.com/images/ingredients/Tabasco%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (407,'Tang','https://thecocktaildb.com/images/ingredients/Tang.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (408,'Vanilla extract','https://thecocktaildb.com/images/ingredients/Vanilla%20extract.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (409,'Vanilla Ice-Cream','https://thecocktaildb.com/images/ingredients/Vanilla%20Ice-Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (410,'Vanilla liqueur','https://thecocktaildb.com/images/ingredients/Vanilla%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (411,'Vanilla schnapps','https://thecocktaildb.com/images/ingredients/Vanilla%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (412,'Vanilla syrup','https://thecocktaildb.com/images/ingredients/Vanilla%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (413,'Vanilla vodka','https://thecocktaildb.com/images/ingredients/Vanilla%20vodka.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (414,'Vanilla','https://thecocktaildb.com/images/ingredients/Vanilla.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (415,'Vermouth','https://thecocktaildb.com/images/ingredients/Vermouth.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (416,'Vinegar','https://thecocktaildb.com/images/ingredients/Vinegar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (417,'Watermelon schnapps','https://thecocktaildb.com/images/ingredients/Watermelon%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (418,'Whipped Cream','https://thecocktaildb.com/images/ingredients/Whipped%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (419,'Whipping Cream','https://thecocktaildb.com/images/ingredients/Whipping%20Cream.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (420,'White chocolate liqueur','https://thecocktaildb.com/images/ingredients/White%20chocolate%20liqueur.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (421,'White Creme de Menthe','https://thecocktaildb.com/images/ingredients/White%20Creme%20de%20Menthe.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (422,'White grape juice','https://thecocktaildb.com/images/ingredients/White%20grape%20juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (423,'White port','https://thecocktaildb.com/images/ingredients/White%20port.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (424,'White Rum','https://thecocktaildb.com/images/ingredients/White%20Rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (425,'White Vinegar','https://thecocktaildb.com/images/ingredients/White%20Vinegar.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (426,'White Wine','https://thecocktaildb.com/images/ingredients/White%20Wine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (427,'Wild Turkey','https://thecocktaildb.com/images/ingredients/Wild%20Turkey.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (428,'Wildberry schnapps','https://thecocktaildb.com/images/ingredients/Wildberry%20schnapps.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (429,'Wine','https://thecocktaildb.com/images/ingredients/Wine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (430,'Worcestershire Sauce','https://thecocktaildb.com/images/ingredients/Worcestershire%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (431,'Yeast','https://thecocktaildb.com/images/ingredients/Yeast.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (432,'Yellow Chartreuse','https://thecocktaildb.com/images/ingredients/Yellow%20Chartreuse.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (433,'Yukon Jack','https://thecocktaildb.com/images/ingredients/Yukon%20Jack.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (434,'Zima','https://thecocktaildb.com/images/ingredients/Zima.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (435,'Caramel Sauce','https://thecocktaildb.com/images/ingredients/Caramel%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (436,'Chocolate Sauce','https://thecocktaildb.com/images/ingredients/Chocolate%20Sauce.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (437,'Lillet Blanc','https://thecocktaildb.com/images/ingredients/Lillet%20Blanc.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (438,'Peach Bitters','https://thecocktaildb.com/images/ingredients/Peach%20Bitters.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (439,'Mini-snickers bars','https://thecocktaildb.com/images/ingredients/Mini-snickers%20bars.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (440,'Prosecco','https://thecocktaildb.com/images/ingredients/Prosecco.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (441,'Salted Chocolate','https://thecocktaildb.com/images/ingredients/Salted%20Chocolate.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (442,'Martini Rosso','https://thecocktaildb.com/images/ingredients/Martini%20Rosso.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (443,'Martini Bianco','https://thecocktaildb.com/images/ingredients/Martini%20Bianco.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (444,'Martini Extra Dry','https://thecocktaildb.com/images/ingredients/Martini%20Extra%20Dry.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (445,'Fresh Lime Juice','https://thecocktaildb.com/images/ingredients/Fresh%20Lime%20Juice.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (446,'Fresh Mint','https://thecocktaildb.com/images/ingredients/Fresh%20Mint.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (447,'Rosemary','https://thecocktaildb.com/images/ingredients/Rosemary.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (448,'Habanero Peppers','https://thecocktaildb.com/images/ingredients/Habanero%20Peppers.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (449,'Ilegal Joven mezcal','https://thecocktaildb.com/images/ingredients/Ilegal%20Joven%20mezcal.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (450,'Elderflower cordial','https://thecocktaildb.com/images/ingredients/Elderflower%20cordial.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (451,'Rosso Vermouth','https://thecocktaildb.com/images/ingredients/Rosso%20Vermouth.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (452,'Creme de Violette','https://thecocktaildb.com/images/ingredients/Creme%20de%20Violette.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (453,'Cocchi Americano','https://thecocktaildb.com/images/ingredients/Cocchi%20Americano.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (454,'White Vermouth','https://thecocktaildb.com/images/ingredients/White%20Vermouth.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (455,'Dry Curacao','https://thecocktaildb.com/images/ingredients/Dry%20Curacao.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (456,'Nocino','https://thecocktaildb.com/images/ingredients/Nocino.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (457,'Averna','https://thecocktaildb.com/images/ingredients/Averna.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (458,'Ramazzotti','https://thecocktaildb.com/images/ingredients/Ramazzotti.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (459,'Fernet-Branca','https://thecocktaildb.com/images/ingredients/Fernet-Branca.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (460,'Allspice Dram','https://thecocktaildb.com/images/ingredients/Allspice%20Dram.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (461,'Falernum','https://thecocktaildb.com/images/ingredients/Falernum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (462,'Singani','https://thecocktaildb.com/images/ingredients/Singani.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (463,'Arrack','https://thecocktaildb.com/images/ingredients/Arrack.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (464,'Blackstrap rum','https://thecocktaildb.com/images/ingredients/Blackstrap%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (465,'Ginger Syrup','https://thecocktaildb.com/images/ingredients/Ginger%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (466,'Honey syrup','https://thecocktaildb.com/images/ingredients/Honey%20syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (467,'Blended Scotch','https://thecocktaildb.com/images/ingredients/Blended%20Scotch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (468,'Islay single malt Scotch','https://thecocktaildb.com/images/ingredients/Islay%20single%20malt%20Scotch.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (469,'151 proof rum','https://thecocktaildb.com/images/ingredients/151%20proof%20rum.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (470,'Absinthe','https://thecocktaildb.com/images/ingredients/Absinthe.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (471,'Creme de Mure','https://thecocktaildb.com/images/ingredients/Creme%20de%20Mure.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (472,'Olive Brine','https://thecocktaildb.com/images/ingredients/Olive%20Brine.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (473,'Pineapple Syrup','https://thecocktaildb.com/images/ingredients/Pineapple%20Syrup.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (474,'St. Germain','https://thecocktaildb.com/images/ingredients/St.%20Germain.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (475,'Lavender','https://thecocktaildb.com/images/ingredients/Lavender.png');
INSERT INTO ingredients(idDrink, strIngredient, strIngredientThumb) VALUES (476,'Whisky','https://thecocktaildb.com/images/ingredients/Whisky.png');
